export const enum ImportTransactionsActionType {
  SET_LOADING = "SetLoading",
  SET_TRANSACTIONS_BANK_ACC_PAIRS = "SetTransactionsBankAccountPairs",
  ADD_API_ERROR = "apiErrors",
  ADD_PARSING_ERRORS = "parsingErrors",

  IMPORT_TXS_FORM_VISIBLE = "ImportTransactionsFormVisible",
  IMPORT_SINGLE_TXS_FORM_VISIBLE = "ImportSingleTransactionsFormVisible",
  EDIT_TXS_FORM_VISIBLE = "EditTransactionsFormVisible",
  SET_EDITED_TRANSACTION = "SetEditedTransaction",
  ADD_TXS_FORM_VISIBLE = "AddTransactionsFormModalVisible",
  MANAGE_FORM_VISIBLE = "ManagePayeeCatDescTagForm",
  ADD_FILTERED_TRANSACTIONS = "AddFilteredTransactions",
  SET_DATA_FETCH_ERROR = "SetDataFetchError",
  SAVE_PAYEE = "SavePayee",
  SAVE_CATEGORY = "SaveCategory",
  SAVE_DESCRIPTION = "SaveDescription",
  SAVE_TAG = "SaveTag",
  DELETE_PAYEE = "DeletePayee",
  DELETE_CATEGORY = "DeleteCategory",
  DELETE_DESCRIPTION = "DeleteDescription",
  DELETE_TAG = "DeleteTag",
  SET_CATEGORIES = "SetCategories",
  SET_DESCRIPTIONS = "SetDescriptions",
  SET_TAGS = "SetTags",
  SET_PAYEES = "SetPayees",
}
